apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-server
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
     containers:
      - image: abhinavsinha001/go-server
        name: go-server
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
  selector:
    app: go-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-server
  labels:
    service-monitor: cm-enabled-app
spec:
  selector:
    matchLabels:
      app: 
  endpoints: go-server
  - port: web
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: go-server-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: go-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: go-server
      metricName: qps
      targetValue: 100

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-server
  namespace: default
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /application
        backend:
          serviceName: go-server
          servicePort: 80
