apiVersion: v1
kind: Service
metadata:
  name: go-server-autoscale
  labels:
    app: go-server-autoscale
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
  selector:
    app: go-server-autoscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-autoscale
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: go-server-autoscale
  template:
    metadata:
      labels:
        app: go-server-autoscale
    spec:
     containers:
      - image: abhinavsinha001/go-server:1.0
        name: go-server-autoscale
        resources:
          limits:
            memory: "16Gi"
            cpu: "4"
          requests:
            memory: "16Gi"
            cpu: "4"
        ports:   
        - name: web
          containerPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-server-autoscale
  labels:
    service-monitor: cm-enabled-app
spec:
  selector:
    matchLabels:
      app: go-server-autoscale
  endpoints:
  - port: web

---

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: go-server-autoscale-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-server-autoscale
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Pods
    pods:
      metricName: http_requests
      targetAverageValue: 100
